/**
 * 由浏览器的 KeyboardEvent.code 到 Electron Accelerator 的映射表。
 * 不用 KeyboardEvent.key 的原因是这个值不稳定，举例：
 * - 不按住 Shift 的情况下按下 1，key 是 1；
 * - 按住 Shift 的情况下按下 1，key 是 !（感叹号）。
 * @see https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_code_values
 * @see https://www.electronjs.org/docs/latest/api/accelerator
 */
export const KeyCode2AcceleratorMap: Record<string, string | undefined> = {
  Escape: 'Escape',
  MediaTrackPrevious: 'MediaPreviousTrack',
  MediaPlayPause: 'MediaPlayPause',
  MediaTrackNext: 'MediaNextTrack',
  MediaStop: 'MediaStop',
  VolumeDown: 'VolumeDown',
  AudioVolumeDown: 'VolumeDown',
  VolumeMute: 'VolumeMute',
  AudioVolumeMute: 'VolumeMute',
  VolumeUp: 'VolumeUp',
  AudioVolumeUp: 'VolumeUp',
  F1: 'F1',
  F2: 'F2',
  F3: 'F3',
  F4: 'F4',
  F5: 'F5',
  F6: 'F6',
  F7: 'F7',
  F8: 'F8',
  F9: 'F9',
  F10: 'F10',
  F11: 'F11',
  F12: 'F12',
  F13: 'F13',
  F14: 'F14',
  F15: 'F15',
  F16: 'F16',
  F17: 'F17',
  F18: 'F18',
  F19: 'F19',
  F20: 'F20',
  F21: 'F21',
  F22: 'F22',
  F23: 'F23',
  F24: 'F24',

  Backquote: '`',
  Digit1: '1',
  Digit2: '2',
  Digit3: '3',
  Digit4: '4',
  Digit5: '5',
  Digit6: '6',
  Digit7: '7',
  Digit8: '8',
  Digit9: '9',
  Digit0: '0',
  Minus: '-',
  Equal: '=',
  Backspace: 'Backspace',

  Tab: 'Tab',
  KeyQ: 'Q',
  KeyW: 'W',
  KeyE: 'E',
  KeyR: 'R',
  KeyT: 'T',
  KeyY: 'Y',
  KeyU: 'U',
  KeyI: 'I',
  KeyO: 'O',
  KeyP: 'P',
  BracketLeft: '[',
  BracketRight: ']',
  Backslash: '\\',

  CapsLock: 'Capslock',
  KeyA: 'A',
  KeyS: 'S',
  KeyD: 'D',
  KeyF: 'F',
  KeyG: 'G',
  KeyH: 'H',
  KeyJ: 'J',
  KeyK: 'K',
  KeyL: 'L',
  Semicolon: ';',
  Quote: "'",
  Enter: 'Enter',

  ShiftLeft: 'Shift',
  KeyZ: 'Z',
  KeyX: 'X',
  KeyC: 'C',
  KeyV: 'V',
  KeyB: 'B',
  KeyN: 'N',
  KeyM: 'M',
  Comma: ',',
  Period: '.',
  Slash: '/',
  ShiftRight: 'Shift',

  ControlLeft: 'Control',
  AltLeft: 'Alt',
  OSLeft: 'Meta',
  MetaLeft: 'Meta',
  Space: 'Space',
  OSRight: 'Meta',
  MetaRight: 'Meta',
  AltRight: 'Alt',
  ControlRight: 'Control',
  ArrowLeft: 'Left',
  ArrowUp: 'Up',
  ArrowDown: 'Down',
  ArrowRight: 'Right',

  NumLock: 'Numlock',
  Numpad0: 'num0',
  Numpad1: 'num1',
  Numpad2: 'num2',
  Numpad3: 'num3',
  Numpad4: 'num4',
  Numpad5: 'num5',
  Numpad6: 'num6',
  Numpad7: 'num7',
  Numpad8: 'num8',
  Numpad9: 'num9',
  NumpadAdd: 'numadd',
  NumpadSubtract: 'numsub',
  NumpadMultiply: 'nummult',
  NumpadDivide: 'numdiv',
  NumpadDecimal: 'numdec',

  ScrollLock: 'Scrolllock',
  PrintScreen: 'PrintScreen',
  Home: 'Home',
  End: 'End',
  PageUp: 'PageUp',
  PageDown: 'PageDown',
  Insert: 'Insert',
  Delete: 'Delete',
}
